import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navigation from './components/navigation';
import {
  ProgressBar,
  ProgressBarProvider,
} from './components/progressComponent';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ProgressBarProvider>
          <ProgressBar className='fixed h-1 shadow-lg shadow-sky-500/20 bg-red-800 top-0' />
          <Navigation />
          {children}
        </ProgressBarProvider>
      </body>
    </html>
  );
}
